### ISSUE TITLE
SemaphoreEthers constructor throws error with localhost on Linux

### ISSUE THREAD

**Issue by agazso** [semaphore-protocol/semaphore#469]
**Describe the bug**
I want to use `SemaphoreEthers` with a locally running hardhat for testing. It works on macOS but on Linux (and therefore on Github as well) the same functionality throws an error:

```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2) 
      at Logger.makeError (node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at JsonRpcProvider.<anonymous> (node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
      at step (node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
      at Object.throw (node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
      at rejected (node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

See an example of running on github [here](https://github.com/logos-innovation-lab/cyphercity-contract/actions/runs/7133465860/job/19426233642?pr=2)

**To Reproduce**
This is the code that I use:

```typescript
const semaphore = new SemaphoreEthers("http://localhost:8545",
  address,
})
```

**Expected behavior**
I would expect this code to work on Linux too.

**Technologies (please complete the following information):**

-   Node.js version: v18.17.1
-   NPM version: 9.6.7
-   Solidity version: 0.8.4

**Comment by vplasencia** [comment]
Hey @agazso ! Try using `http://127.0.0.1:8545` instead.

We had a similar issue before with `ethers` and we fixed it with that:
https://github.com/privacy-scaling-explorations/bandada/pull/218

This helped us fix it:
https://github.com/ethers-io/ethers.js/discussions/1398#discussioncomment-3528631

**Comment by agazso** [comment]
Thanks @vplasencia, that works!

**Comment by agazso** [comment]
On a second thought it would be good to update the documentation here:
https://semaphore.pse.dev/docs/guides/fetching-data#fetch-data-using-semaphoreethers

I copied the non-working code from there and then it would help others to avoid running into the same issue.

**Comment by vplasencia** [comment]
Yes, that's a great idea @agazso. Thank you so much for pointing it out and updating it. I just added the same issue for the Semaphore boilerplate:
https://github.com/semaphore-protocol/boilerplate/issues/47
